run:
  timeout: 10m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  - exportloopref
  - gocritic
  - godot
  - gofmt
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - misspell
  - nilerr
  - noctx
  - nolintlint
  - nosprintfhostport
  - prealloc
  - revive
  - staticcheck
  - unconvert
  - unused
  - usestdlibvars
  - whitespace
